const employee = [
  {
    id: "E001",
    firstName: "Amit",
    email: "employee1@example.com",
    password: "123",
    taskNumber: 3,
    taskTypes: {
      active: 2,
      new: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        title: "Task 1",
        description: "Complete the monthly report.",
        date: "2024-12-30",
        category: "Report",
        active: true,
        new: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2",
        description: "Attend team meeting on project updates.",
        date: "2024-12-28",
        category: "Meeting",
        active: true,
        new: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 3",
        description: "Review the client feedback and make changes.",
        date: "2024-12-25",
        category: "Client",
        active: false,
        new: false,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    id: "E002",
    firstName: "Priya",
    email: "employee2@example.com",
    password: "123",
    taskNumber: 3,
    taskTypes: {
      active: 2,
      new: 2,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        title: "Task 1",
        description: "Update project documentation.",
        date: "2024-12-29",
        category: "Documentation",
        active: true,
        new: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2",
        description: "Test the new product feature.",
        date: "2024-12-31",
        category: "Testing",
        active: true,
        new: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 3",
        description: "Fix critical bug reported by QA.",
        date: "2024-12-26",
        category: "Bug Fix",
        active: false,
        new: false,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    id: "E003",
    firstName: "Ravi",
    email: "employee3@example.com",
    password: "123",
    taskNumber: 2,
    taskTypes: {
      active: 2,
      new: 0,
      completed: 0,
      failed: 0,
    },
    tasks: [
      {
        title: "Task 1",
        description: "Prepare the marketing presentation.",
        date: "2024-12-27",
        category: "Marketing",
        active: true,
        new: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2",
        description: "Analyze sales employees and prepare report.",
        date: "2024-12-29",
        category: "Sales",
        active: true,
        new: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: "E004",
    firstName: "Neha",
    email: "employee4@example.com",
    password: "123",
    taskNumber: 3,
    taskTypes: {
      active: 3,
      new: 2,
      completed: 0,
      failed: 0,
    },
    tasks: [
      {
        title: "Task 1",
        description: "Organize office supplies inventory.",
        date: "2024-12-26",
        category: "Inventory",
        active: true,
        new: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2",
        description: "Schedule team-building activities.",
        date: "2024-12-28",
        category: "Team Building",
        active: true,
        new: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 3",
        description: "Assist with onboarding new employees.",
        date: "2024-12-31",
        category: "HR",
        active: true,
        new: true,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: "E005",
    firstName: "Kiran",
    email: "employee5@example.com",
    password: "123",
    taskNumber: 4,
    taskTypes: {
      active: 2,
      new: 2,
      completed: 2,
      failed: 0,
    },
    tasks: [
      {
        title: "Task 1",
        description: "Prepare financial statements for review.",
        date: "2024-12-30",
        category: "Finance",
        active: true,
        new: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2",
        description: "Coordinate with vendors for supplies order.",
        date: "2024-12-28",
        category: "Procurement",
        active: false,
        new: false,
        completed: true,
        failed: false,
      },
      {
        title: "Task 3",
        description: "Complete HR compliance training.",
        date: "2024-12-25",
        category: "Training",
        active: true,
        new: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 4",
        description: "Prepare a report on quarterly expenses.",
        date: "2024-12-29",
        category: "Finance",
        active: false,
        new: false,
        completed: true,
        failed: false,
      },
    ],
  },
];

const admin = [
  {
    id: "A001",
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employee", JSON.stringify(employee));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employee = JSON.parse(localStorage.getItem("employee"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employee, admin };
};
